# Generated by Django 4.1.7 on 2023-04-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smart_emailApp", "0014_emailtask_last_sent_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myjobmodel",
            name="job_id",
        ),
    ]
