# Generated by Django 4.1.7 on 2023-05-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_emailApp", "0015_remove_myjobmodel_job_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("decription", models.CharField(blank=True, max_length=450, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
