# Generated by Django 4.1.7 on 2023-06-23 01:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smart_emailApp", "0017_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
