# Generated by Django 4.1.7 on 2023-06-23 02:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smart_emailApp", "0018_alter_emails_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="product1_name",
            field=ckeditor.fields.RichTextField(blank=True, max_length=60, null=True),
        ),
    ]
