# Generated by Django 4.1.7 on 2023-06-23 02:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_emailApp", "0019_alter_emails_product1_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="product1_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emails",
            name="product1_name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="emails",
            name="product2_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emails",
            name="product3_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emails",
            name="product4_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailtask",
            name="task_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
